spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:h2:file:./target/arctic-tern-db;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false
